use crate::accelerated_transition_system::AcceleratedTransitionSystemEngine;
use crate::induced_v_map::InducedVMapEngine;
use num_bigint::BigUint;

/// Result of evaluating one deterministic zero-lift step from endpoint y_s.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ZeroLiftStepResult {
    pub j: u64,
    pub residual_e: BigUint,
    pub next_endpoint_z: BigUint,
    pub next_odd_multiplier: BigUint,
    pub next_total_precision: u64,
}

/// Canonical Prefix State (0 <= \rho_s < 2^{B_s}).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CanonicalPrefixState {
    pub total_precision: u64,
    pub odd_multiplier: BigUint,
    pub source_residue: BigUint,
    pub endpoint_z: BigUint,
}

/// Concrete Orbit State for arbitrary initial z_0 = C_{j_0} + M_{j_0} * n_0.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConcreteOrbitState {
    pub initial_z: BigUint,
    pub current_z: BigUint,
    pub gap_history: Vec<u64>,
}

/// Stabilized Source Tail State (z_0 = \rho and z_0 < 2^{B_s}).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StabilizedSourceTailState {
    pub source_z0: BigUint,
    pub current_precision: u64,
    pub is_fully_stabilized: bool,
}

/// Deterministic O(1)-per-step zero-lift continuation engine.
pub struct ZeroLiftContinuationEngine;

impl ZeroLiftContinuationEngine {
    /// Exact arbitrary-j successor solver for endpoint y_s.
    /// Returns Some(j) if y_s lies in zero-lift branch C_j \pmod{M_j}, otherwise None.
    pub fn find_exact_successor(y_s: &BigUint) -> Result<Option<u64>, String> {
        let t = BigUint::from(1u32) + (BigUint::from(11u32) * y_s);
        let val = BigUint::from(231u32) + (BigUint::from(729u32) * &t);

        let delta = val.trailing_zeros().unwrap_or(0);
        if delta < 1 || (delta - 1) % 4 != 0 {
            return Ok(None);
        }

        let j = (delta - 1) / 4;
        let branch_j = InducedVMapEngine::get_branch_normal_form(j)?;

        if y_s % &branch_j.modulus_c == branch_j.c_j_normalized {
            Ok(Some(j))
        } else {
            Ok(None)
        }
    }

    /// Evaluates exact zero-lift step from endpoint y_s using exact successor solver.
    pub fn step(
        y_s: &BigUint,
        current_odd_mult: &BigUint,
        current_prec: u64,
    ) -> Result<Option<ZeroLiftStepResult>, String> {
        if let Some(j) = Self::find_exact_successor(y_s)? {
            let branch_j = InducedVMapEngine::get_branch_normal_form(j)?;
            let m_j = &branch_j.modulus_c;

            let residual_e = (y_s - &branch_j.c_j_normalized) / m_j;
            let next_z = &branch_j.d_j_normalized + (&branch_j.multiplier_d * &residual_e);
            let next_odd = current_odd_mult * &branch_j.multiplier_d;
            let next_prec = current_prec + 9 + 4 * j;

            Ok(Some(ZeroLiftStepResult {
                j,
                residual_e,
                next_endpoint_z: next_z,
                next_odd_multiplier: next_odd,
                next_total_precision: next_prec,
            }))
        } else {
            Ok(None)
        }
    }

    /// Canonical child state generated by initial block j_0 from empty prefix state.
    /// Initial block lift \Lambda_1(\epsilon) = C_{j_0} selects source cylinder \rho_1 = C_{j_0}.
    pub fn canonical_child_from_initial_block(j_0: u64) -> Result<CanonicalPrefixState, String> {
        let branch = InducedVMapEngine::get_branch_normal_form(j_0)?;
        Ok(CanonicalPrefixState {
            total_precision: 9 + 4 * j_0,
            odd_multiplier: branch.multiplier_d,
            source_residue: branch.c_j_normalized,
            endpoint_z: branch.d_j_normalized,
        })
    }

    /// Parameterized generator for pure-j=0 witness z_0 executing at least `length` consecutive j=0 steps.
    /// Theorem: z_0 \equiv 86208 * (-217)^{-1} \pmod{2^{9 + 4 * length}} executes length steps of j=0.
    pub fn pure_zero_gap_witness(length: usize) -> Result<BigUint, String> {
        if length == 0 {
            return Ok(BigUint::from(342u32)); // C_0
        }

        let n_bits = (9 * (length + 1)) as u32;
        let modulus = BigUint::from(1u32) << n_bits;

        // Solve 217 * z^* \equiv -26 \pmod{2^N} => z^* = (2^N - 26) * 217^{-1} \pmod{2^N}
        let num = &modulus - BigUint::from(26u32);
        let denom = BigUint::from(217u32);
        let denom_inv = AcceleratedTransitionSystemEngine::mod_inverse_pow2(&denom, n_bits);

        let z_0 = (&num * &denom_inv) % &modulus;

        Ok(z_0)
    }

    /// Traces zero-lift suffix run starting from canonical child state y_1 = D_{j_0}.
    pub fn trace_zero_lift_suffix(
        j_0: u64,
        max_steps: usize,
    ) -> Result<(CanonicalPrefixState, Vec<ZeroLiftStepResult>), String> {
        let child = Self::canonical_child_from_initial_block(j_0)?;
        let mut steps = Vec::new();

        let mut curr_y = child.endpoint_z.clone();
        let mut curr_odd = child.odd_multiplier.clone();
        let mut curr_prec = child.total_precision;

        for _ in 0..max_steps {
            if let Some(res) = Self::step(&curr_y, &curr_odd, curr_prec)? {
                curr_y = res.next_endpoint_z.clone();
                curr_odd = res.next_odd_multiplier.clone();
                curr_prec = res.next_total_precision;
                steps.push(res);
            } else {
                break;
            }
        }

        Ok((child, steps))
    }
}
